import { CompanyProfile, SavedProduct, HistoryItem, InvoiceDocument, VoicePersona, AICallSession } from '../types';

export const DEFAULT_COMPANY: CompanyProfile = {
  name: 'Boutique Éclat & Style',
  sector: 'Boutique & Prêt-à-porter',
  description: 'Vêtements tendance, prêt-à-porter masculin et féminin, chaussures chics et accessoires de mode avec un service client attentionné.',
  phone: '+221 77 123 45 67',
  whatsapp: '+221 77 123 45 67',
  address: 'Avenue Bourguiba, Dakar',
  hours: 'Lun - Sam : 09h00 - 20h00',
  currency: 'FCFA',
  defaultTone: 'Professionnel et Chaleureux',
  websiteOrSocial: '@eclat_style_dakar',
  knowledgeBase: 'Livraison gratuite à partir de 50 000 FCFA d’achat. Expédition partout en 24h/48h. Échange possible sous 7 jours sur présentation du reçu.',
  targetAudienceDefault: 'Jeunes professionnels, femmes actives et amateurs de mode soignée',
};

export const SECTOR_TEMPLATES: Record<string, Partial<CompanyProfile>> = {
  'Boutique de Mode': {
    name: 'Boutique Éclat & Style',
    sector: 'Boutique & Prêt-à-porter',
    description: 'Vêtements tendance, accessoires de mode et maroquinerie de qualité.',
    phone: '+221 77 123 45 67',
    whatsapp: '+221 77 123 45 67',
    address: 'Avenue Bourguiba, Dakar',
    hours: 'Lun - Sam : 09h - 20h',
    currency: 'FCFA',
    defaultTone: 'Élégant et Haut de Gamme',
    knowledgeBase: 'Livraison gratuite dès 50 000 FCFA. Possibilité d’essayer à la livraison sur Dakar.',
  },
  'Restaurant / Traiteur': {
    name: 'La Table Gourmande',
    sector: 'Restaurant & Alimentation',
    description: 'Cuisine traditionnelle et moderne, grillades, plats du jour frais, service sur place, à emporter et livraison.',
    phone: '+225 07 45 67 89',
    whatsapp: '+225 07 45 67 89',
    address: 'Boulevard de Marseille, Abidjan',
    hours: 'Mardi - Dimanche : 11h30 - 23h00',
    currency: 'FCFA',
    defaultTone: 'Familial et Accessible',
    knowledgeBase: 'Menu du jour renouvelé chaque matin. Commande WhatsApp avant 11h pour livraison garantie à 12h30.',
  },
  'E-commerce & Vente en ligne': {
    name: 'TechNova Express',
    sector: 'E-commerce & Vente en ligne',
    description: 'Accessoires high-tech, montres connectées, gadgets innovants et livraison rapide à domicile.',
    phone: '+221 78 001 22 33',
    whatsapp: '+221 78 001 22 33',
    address: 'Boutique 100% en ligne',
    hours: 'Service client WhatsApp : 24h/7j',
    currency: 'FCFA',
    defaultTone: 'Dynamique et Vendeur',
    knowledgeBase: 'Paiement à la livraison accepté (Wave / Orange Money / Cash). Garantie constructeur 6 mois.',
  },
  'Salon de Beauté & Bien-être': {
    name: 'Studio Douceur & Beauté',
    sector: 'Beauté, Coiffure & Bien-être',
    description: 'Soins du visage, tresses et coiffure, manucure et conseils beauté sur mesure.',
    phone: '+225 05 55 44 33',
    whatsapp: '+225 05 55 44 33',
    address: 'Cocody Angré, Abidjan',
    hours: 'Mar - Sam : 09h00 - 19h30 sur RDV',
    currency: 'FCFA',
    defaultTone: 'Professionnel et Chaleureux',
    knowledgeBase: 'Réservation conseillée 24h à l’avance par WhatsApp. Réduction de 10% pour toute première visite.',
  },
  'Artisan & Prestations B2B': {
    name: 'Atelier Rénov & Bâtiment',
    sector: 'Artisanat & Fait-main',
    description: 'Menuiserie sur-mesure, agencement d’intérieur, peinture et rénovation artisanale de qualité.',
    phone: '+221 76 887 66 55',
    whatsapp: '+221 76 887 66 55',
    address: 'Zone Industrielle, Dakar',
    hours: 'Lun - Ven : 08h00 - 18h00',
    currency: 'FCFA',
    defaultTone: 'Direct et Efficace',
    knowledgeBase: 'Devis détaillé gratuit sous 24h. Garantie décennale et matériaux certifiés.',
  },
};

export const INITIAL_PRODUCTS: SavedProduct[] = [
  {
    id: 'prod-1',
    name: 'Veste Blazer Tailleur Cintrée',
    price: 45000,
    category: 'Vêtements Femme',
    features: 'Tissu stretch respirant, boutons dorés gravés, coupe italienne ajustée.',
    benefits: 'Sublime la silhouette, convient au bureau comme aux sorties de soirée, infroissable.',
    targetAudience: 'Femmes actives et élégantes de 25 à 50 ans',
    generatedTitle: 'Veste Blazer Cintrée Élégance – Sublimez Votre Allure au Quotidien',
    generatedDescription:
      "Alliez prestance et confort absolu avec notre blazer cintrée coupe italienne. Fabriquée dans un tissu stretch haut de gamme infroissable, elle s'adapte avec souplesse à tous vos mouvements tout en soulignant votre silhouette avec élégance. Finitions soignées avec boutons dorés exclusifs.",
    keyBulletPoints: [
      'Coupe cintrée flatteuse adaptée à toutes les morphologies',
      'Matière infroissable et ultra confortable pour toute la journée',
      'Idéale pour le travail, réunions importantes et soirées',
    ],
    callToAction: 'Commandez la vôtre dès aujourd’hui et profitez de la livraison offerte !',
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
  {
    id: 'prod-2',
    name: 'Sac à Main Cuir Minimaliste',
    price: 65000,
    category: 'Maroquinerie',
    features: 'Cuir véritable pleine fleur, bandoulière amovible, compartiment tablette.',
    benefits: 'Ultra résistant, intemporel et fonctionnel pour transporter tous vos essentiels.',
    targetAudience: 'Amateurs de design épuré et de maroquinerie durable',
    generatedTitle: 'Sac à Main en Cuir Pleine Fleur – L’Essentiel Chic & Durable',
    generatedDescription:
      "L'accessoire indispensable pour parfaire votre garde-robe. Confectionné à la main en cuir véritable pleine fleur, ce sac allie robustesse légendaire et esthétique minimaliste contemporaine. Doté d'une bandoulière modulable et de poches intelligentes.",
    keyBulletPoints: [
      '100% Cuir pleine fleur résistant aux intempéries',
      'Compartiment renforcé pour tablette et smartphone',
      'Fermeture éclair sécurisée et finitions laiton brossé',
    ],
    callToAction: 'Stock limité en boutique – Réservez le vôtre en un clic par WhatsApp !',
    createdAt: new Date(Date.now() - 3600000 * 48).toISOString(),
  },
];

export const INITIAL_HISTORY: HistoryItem[] = [
  {
    id: 'hist-1',
    type: 'social',
    title: 'Post Instagram - Lancement Nouvelle Collection',
    inputSummary: 'Veste Blazer et Sac Cuir - Nouvelle Collection Automne',
    output:
      '✨ Révélez votre élégance avec notre nouvelle collection automne ! 🍂\n\nDes pièces pensées pour vous sublimer au quotidien : confort absolu, finitions soignées et style intemporel.\n\n📍 Rendez-vous au 14 Rue du Commerce ou commandez par WhatsApp au +33 6 12 34 56 78.\n\n#ModeParis #NouvelleCollection #LookDuJour #StyleEtConfort',
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: 'hist-2',
    type: 'client_reply',
    title: 'Réponse WhatsApp - Demande de disponibilité taille M',
    inputSummary: 'Client demande si la veste blazer est disponible en taille M',
    output:
      'Bonjour Sophie ! 👋 Oui, la Veste Blazer Cintrée est bien disponible en taille M dans notre boutique ! Souhaitez-vous que nous vous mettions une pièce de côté pour aujourd’hui, ou préférez-vous une livraison à domicile ? 😊',
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
];

export const INITIAL_INVOICES: InvoiceDocument[] = [
  {
    id: 'inv-1',
    type: 'invoice',
    number: 'FAC-2026-001',
    date: new Date(Date.now() - 86400000 * 2).toISOString().slice(0, 10),
    dueDate: new Date(Date.now() + 86400000 * 5).toISOString().slice(0, 10),
    clientName: 'Aïssatou Traoré',
    clientCompany: 'Cabinet Conseil Horizon',
    clientPhone: '+221 77 555 44 33',
    clientEmail: 'aissatou.traore@horizon-conseil.sn',
    clientAddress: 'Plateau, Immeuble Horizon, Dakar',
    items: [
      {
        id: 'item-1',
        description: 'Veste Blazer Tailleur Cintrée (Taille M, Bleu Nuit)',
        quantity: 2,
        unitPrice: 45000,
        taxRate: 0,
        total: 90000,
      },
      {
        id: 'item-2',
        description: 'Sac à Main Cuir Minimaliste (Coloris Camel)',
        quantity: 1,
        unitPrice: 65000,
        taxRate: 0,
        total: 65000,
      },
      {
        id: 'item-3',
        description: 'Frais de livraison express à domicile (Dakar Plateau)',
        quantity: 1,
        unitPrice: 3000,
        taxRate: 0,
        total: 3000,
      },
    ],
    discountType: 'fixed',
    discountValue: 5000,
    taxRate: 0,
    status: 'pending',
    notes: 'Merci pour votre confiance ! Merci d’indiquer le numéro de facture FAC-2026-001 lors de votre virement ou transfert Mobile Money.',
    paymentTerms: 'Paiement à réception par Wave, Orange Money ou virement bancaire.',
    paymentDetails: {
      mobileMoneyNumber: '+221 77 123 45 67',
      mobileMoneyProvider: 'Wave / Orange Money',
      bankName: 'CBAO Attijariwafa Bank',
      ibanOrRib: 'SN012 01001 12345678901 45',
    },
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'inv-2',
    type: 'quote',
    number: 'DEV-2026-004',
    date: new Date().toISOString().slice(0, 10),
    dueDate: new Date(Date.now() + 86400000 * 14).toISOString().slice(0, 10),
    clientName: 'Mamadou Diallo',
    clientCompany: 'Hôtel Les Almadies Resort',
    clientPhone: '+221 76 987 11 22',
    clientEmail: 'achats@lesalmadies.sn',
    clientAddress: 'Route des Almadies, Dakar',
    items: [
      {
        id: 'item-10',
        description: 'Tenues professionnelles de réception avec broderie logo sur mesure',
        quantity: 6,
        unitPrice: 35000,
        taxRate: 18,
        total: 210000,
      },
      {
        id: 'item-11',
        description: 'Foulards en soie coordonnés aux couleurs de l’établissement',
        quantity: 6,
        unitPrice: 8500,
        taxRate: 18,
        total: 51000,
      },
      {
        id: 'item-12',
        description: 'Étalonnage, essayages sur place et retouches sur mesure incluses',
        quantity: 1,
        unitPrice: 25000,
        taxRate: 18,
        total: 25000,
      },
    ],
    discountType: 'percent',
    discountValue: 5,
    taxRate: 18,
    status: 'sent',
    notes: 'Devis valable 14 jours ouvrés. Acompte de 50% à la validation de la commande, solde à la livraison.',
    paymentTerms: '50% d’acompte à la signature, solde sous 15 jours après livraison.',
    paymentDetails: {
      mobileMoneyNumber: '+221 77 123 45 67',
      mobileMoneyProvider: 'Wave / Orange Money',
      bankName: 'Société Générale Sénégal',
      ibanOrRib: 'SN053 01002 98765432109 88',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const VOICE_PERSONAS: VoicePersona[] = [
  {
    id: 'amina',
    name: 'Amina',
    role: 'Relation Client & Suivi Commandes',
    gender: 'female',
    accentDesc: 'Voix féminine chaleureuse, posée, bienveillante et très polie',
    pitch: 1.1,
    rate: 1.0,
    avatarColor: 'from-pink-500 to-rose-600',
    sampleGreeting: 'Bonjour ! C’est Amina, votre conseillère dédiée chez notre entreprise. J’espère que vous passez une excellente journée !',
  },
  {
    id: 'koffi',
    name: 'Koffi',
    role: 'Conseiller Commercial & Devis',
    gender: 'male',
    accentDesc: 'Voix masculine posée, diplomate, rassurante et engageante',
    pitch: 0.95,
    rate: 0.98,
    avatarColor: 'from-indigo-600 to-blue-700',
    sampleGreeting: 'Bonjour, ici Koffi du service commercial. Je vous contacte très brièvement pour faire le point sur votre proposition et répondre à vos questions.',
  },
  {
    id: 'fatou',
    name: 'Fatou',
    role: 'Expéditions & Enquêtes Satisfaction',
    gender: 'female',
    accentDesc: 'Voix féminine dynamique, souriante, enthousiaste et réactive',
    pitch: 1.15,
    rate: 1.05,
    avatarColor: 'from-amber-500 to-orange-600',
    sampleGreeting: 'Allô bonjour ! C’est Fatou de l’équipe de livraison. Je vous appelle pour vous confirmer la bonne préparation de votre colis !',
  },
  {
    id: 'jean',
    name: 'Jean',
    role: 'Comptabilité & Recouvrement Amiable',
    gender: 'male',
    accentDesc: 'Voix masculine claire, respectueuse, ferme et professionnelle',
    pitch: 0.9,
    rate: 0.95,
    avatarColor: 'from-slate-700 to-slate-900',
    sampleGreeting: 'Bonjour, Jean du service comptabilité et facturation. Je vous appelle en toute courtoisie au sujet du règlement de votre dernière facture.',
  },
];

export const INITIAL_CALL_SESSIONS: AICallSession[] = [
  {
    id: 'call-1',
    contactName: 'Aïssatou Traoré',
    contactPhone: '+221 77 555 44 33',
    contactCompany: 'Cabinet Conseil Horizon',
    scenario: 'payment_reminder',
    voicePersonaId: 'jean',
    documentRef: 'FAC-2026-001',
    amountDue: 153000,
    objective: 'Relance courtoise de la facture FAC-2026-001 de 153 000 FCFA avec proposition de paiement Wave ou virement.',
    turns: [
      {
        speaker: 'ai',
        text: 'Bonjour Madame Aïssatou Traoré ! C’est Jean, l’assistant comptable de Boutique Éclat & Style. J’espère que vous allez très bien ?',
        suggestedCustomerReplies: ['Bonjour Jean, oui très bien merci.', 'Oui, qui est à l’appareil ?', 'Bonjour, de quoi s’agit-il ?'],
      },
      {
        speaker: 'customer',
        text: 'Bonjour Jean, oui très bien merci !',
      },
      {
        speaker: 'ai',
        text: 'Je vous contacte en toute courtoisie concernant la facture FAC-2026-001 de 153 000 FCFA pour votre ensemble blazer et sac cuir livrés la semaine passée. Le délai arrive bientôt à échéance.',
        suggestedCustomerReplies: ['Oui j’ai bien reçu, je règle par Wave aujourd’hui.', 'Pouvez-vous me renvoyer la facture sur WhatsApp ?', 'J’ai déjà fait le virement ce matin.'],
      },
      {
        speaker: 'customer',
        text: 'Oui j’ai bien reçu la facture, je prévois de régler par Wave aujourd’hui même.',
      },
      {
        speaker: 'ai',
        text: 'C’est parfait, merci beaucoup pour votre réactivité ! Je vous renvoie immédiatement notre numéro Wave officiel par message WhatsApp pour vous faciliter l’opération. Excellente fin de journée à vous !',
        suggestedCustomerReplies: ['Merci beaucoup, bonne journée !', 'D’accord, j’attends votre message.'],
      },
    ],
    fullScript: `[Assistant IA - Jean] : Bonjour Madame Aïssatou Traoré ! C’est Jean, l’assistant comptable de Boutique Éclat & Style. J’espère que vous allez très bien ?
[Cliente] : Bonjour Jean, oui très bien merci !
[Assistant IA - Jean] : Je vous contacte en toute courtoisie concernant la facture FAC-2026-001 de 153 000 FCFA. Le délai arrive bientôt à échéance. Souhaitez-vous régler par Wave ou par virement bancaire ?
[Cliente] : Oui j’ai bien reçu, je règle par Wave aujourd’hui même.
[Assistant IA - Jean] : C’est parfait, merci beaucoup pour votre réactivité ! Je vous renvoie immédiatement notre numéro Wave officiel par message WhatsApp. Excellente journée à vous !`,
    whatsappFollowUpMessage: `Bonjour Madame Aïssatou Traoré, suite à notre échange téléphonique avec notre assistant vocal, voici le récapitulatif pour le règlement de votre facture FAC-2026-001 d’un montant de 153 000 FCFA :
💳 Numéro Wave officiel : +221 77 123 45 67
Merci pour votre fidélité et excellente journée ! Boutique Éclat & Style`,
    status: 'completed',
    durationSeconds: 42,
    notes: 'Cliente agréable. Confirmation de règlement par Wave aujourd’hui.',
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
];

